name: "tools: check release"

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    name: Check and tag new release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-tags: true

      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          latest=$(curl -s 'https://dl.google.com/android/repository/repository2-3.xml' | grep -oP 'commandlinetools-linux-\K[0-9]+(?=_latest\.zip)' | sort -n | tail -1)
          if ! git ls-remote --exit-code origin "refs/tags/tools-$latest"; then
            gh workflow run release-tools.yml -f version="$latest"
          fi
